Repository lfn-cnti/testsuite, pull requests merged in 2020-07, with the labels that each got.

#298 Ephemeral Dev Tool cncf/cnf-conformance#206
  .gitignore
  tools/ephemeral_env/Dockerfile
  tools/ephemeral_env/ephemeral_env.cr
Labels: PoC

#302 Add version command
  .gitignore
  .travis.yml
  cnf-conformance.env.example
  spec/cnf_conformance_spec.cr
  spec/utils/release_manager_spec.cr
  spec/utils/utils_spec.cr
  src/cnf-conformance.cr
  src/cnf_conformance.cr
  src/tasks/utils/release_manager.cr
  src/tasks/utils/utils.cr
Labels: 5 pts

#303 #284 asset upload now compares local hash with remote master hash
  spec/utils/release_manager_spec.cr
  src/tasks/utils/release_manager.cr
Labels: 1 pt

#304 Force version name change head > master
  src/tasks/utils/release_manager.cr
Labels: 1 pt

#305 Version command#284 Uploading corrupted files
  src/tasks/utils/release_manager.cr
Labels: 1 pt

#309 Ephemeral dev env#206 Documentation
  src/tasks/utils/release_manager.cr
  tools/ephemeral_env/README.md
Labels: 2 pts

#313 Ephemeral dev env#206 Static build
  src/tasks/utils/release_manager.cr
Labels: 1 pt

#318 #206 documentation update
  tools/ephemeral_env/README.md
Labels: 1 pt

#316 Feature/automated release manager 306
  .travis.yml
  src/tasks/utils/release_manager.cr
Labels: 1 pt
