Repository lfn-cnti/testsuite, pull requests merged in 2020-06, with the labels that each got.

#235 Update regexp used by kubectl_version function
  spec/utils/system_information/curl_spec.cr
  spec/utils/system_information/kubectl_spec.cr
  spec/utils/system_information/wget_spec.cr
  src/tasks/utils/system_information/kubectl.cr
Labels: bug

#241 Bugfix: microservice test doesn't clean up envoy
  .travis.yml
  shard.lock
  shard.yml
  spec/microservice_spec.cr
Labels: beta-test, bug, sprint8

#250 Whitelisting kube-multus in CoreDNS example
  example-cnfs/coredns/cnf-conformance.yml
Labels: beta-test

#252 Updated points.yml to only have implemented tests enabled
  points-all.yml
  points.yml
Labels: beta-test, bug

#254 BUGFIX: Deployment wait output now using logger
  src/tasks/utils/sample_utils.cr
Labels: beta-test, bug

#253 need kube-multus whitelisted because beta test clusters have multus i…
  example-cnfs/coredns/cnf-conformance.yml
Labels: enhancement

#255 Deployment wait output to make defaults quieter
  src/tasks/utils/sample_utils.cr
Labels: beta-test, bug

#257 Adding 📶☠️ emoji to chaos network test #157
  src/tasks/resilience.cr
Labels: emoji

#259 Increase timeout for startup time test
  config.yml
  points-all.yml
  points.yml
  sample-cnfs/sample_envoy_slow_startup/chart/templates/deployment.yaml
  scoring_config/points-beta1.yml
  spec/microservice_spec.cr
  src/tasks/microservice.cr
Labels: beta-test, bug

#276 updating README, Test Categories and Install Guide
  INSTALL.md
  README.md
  TEST-CATEGORIES.md
Labels: documentation

#289 Upsert now stop double counting of test scores
  spec/utils/utils_spec.cr
  src/tasks/resilience.cr
  src/tasks/statelessness.cr
  src/tasks/utils/utils.cr
Labels: 3 pts

#290 Update how and when results are saved so a repeated warning for overwriting results.yml does not occur
  .gitignore
  spec/utils/utils_spec.cr
  src/cnf-conformance.cr
  src/tasks/cleanup.cr
  src/tasks/setup.cr
  src/tasks/utils/sample_utils.cr
  src/tasks/utils/utils.cr
Labels: 5 pts
