Repository lfn-cnti/testsuite, pull requests merged in 2020-04, with the labels that each got.

#131 Proof of Concept: Add feature toggles to the CNF Conformance suite
  .github/PULL_REQUEST_TEMPLATE.md
  INSTALL.md
  spec/utils_spec.cr
  src/cnf_conformance.cr
  src/tasks/utils/utils.cr
Labels: enhancement

#139 Updates to documentation on example CNFs
  EXAMPLE-CNFS.md
Labels: documentation

#138 WIP Updating Vendor reference to say CNF Developer
  INSTALL.md
Labels: documentation

#171 Added CNF setup and cleanup instructions
  INSTALL.md
Labels: cnf developer, documentation, enhancement

#172 Updating example to match upstream example service chain (vs single CNF)
  example-cnfs/ip-forwarder/README.md
  example-cnfs/vpp-3c2n-csp-use-case/README.md
  example-cnfs/vpp-3c2n-csp-use-case/cnf-conformance.yml
  example-cnfs/vpp-3c2n-csp-use-case/csp/.helmignore
  example-cnfs/vpp-3c2n-csp-use-case/csp/Chart.yaml
  example-cnfs/vpp-3c2n-csp-use-case/csp/templates/_helpers.tpl
  example-cnfs/vpp-3c2n-csp-use-case/csp/templates/configmap.yaml
  example-cnfs/vpp-3c2n-csp-use-case/csp/templates/deployment.yaml
  example-cnfs/vpp-3c2n-csp-use-case/csp/values.yaml
Labels: example CNF

#177 Bugfix for VPP IP Forwarder example
  example-cnfs/ip-forwarder/vpp/templates/configmap.yaml
Labels: bug, example CNF

#187 Setting a image release for the current examples
  example-cnfs/envoy/cnf-conformance.yml
  example-cnfs/ip-forwarder/cnf-conformance.yml
  example-cnfs/vpp-3c2n-csp-use-case/cnf-conformance.yml
Labels: enhancement
