Repository lfn-cnti/testsuite, pull requests merged in 2020-05, with the labels that each got.

#190 Adding emoji, 📊🖛 🌐, to published helm chart test
  src/tasks/installability.cr
Labels: emoji

#195 Using unicode ⎯➤ instead of emoji arrow in published helm chart test
  src/tasks/installability.cr
Labels: emoji

#185 Adds CoreDNS as an example CNF
  example-cnfs/coredns/README.md
  example-cnfs/coredns/cnf-conformance.yml
Labels: example CNF

#196 Fix hardcoded conformance directory path1
  spec/utils/sample_utils_spec.cr
Labels: bug

#211 Steps for adding Multus and CNIs to Kind
  KIND-INSTALL.md
Labels: documentation

#197 Emoji for pass fail
  src/tasks/configuration_lifecycle.cr
  src/tasks/installability.cr
  src/tasks/microservice.cr
  src/tasks/platform/platform.cr
  src/tasks/security.cr
Labels: emoji
