Repository lfn-cnti/testsuite, pull requests merged in 2020-08, with the labels that each got.

#331 #301 curl now supports new cnf-conformance binary names
  curl_install.sh
Labels: 1 pt

#329 Create code-of-conduct.md
  code-of-conduct.md
Labels: process

#332 Add linter and usage doc
  USAGE.md
  shard.lock
  shard.yml
Labels: documentation, enhancement
