Repository lfn-cnti/testsuite, pull requests merged in 2021-04, with the labels that each got.

#704 [BUG] tags for points.yml scores are getting added for workload reslilience tests when they're tagged as platform:resilience
  spec/utils/cnf_manager_spec.cr
  src/tasks/utils/points.cr
Labels: 3 pts

#716 switch from wget to curl
  README-testsuite.md
Labels: documentation

#722 moving quick start to top
  README.md
Labels: documentation, usability

#726 updated quick install links for download
  INSTALL.md
  README.md
  SOURCE_INSTALL.md
Labels: documentation

#751 Feature/#724 more link fixes and updates of cnf-conformance to cnf-testsuite where applicable
  CNF_CONFORMANCE_YML_USAGE.md
  CONTRIBUTING.md
  FAQ.md
  INSTALL.md
  README.md
  SOURCE_INSTALL.md
  USAGE.md
  embedded_files/POINTS.md
  example-cnfs/coredns/README.md
  example-cnfs/envoy/README.md
  example-cnfs/ip-forwarder/README.md
  example-cnfs/linkerd2/README.md
  example-cnfs/nsm/README.md
  example-cnfs/pantheon-nsm-nat/README.md
  example-cnfs/vpp-3c2n-csp-use-case/README.md
  tools/curl_install_tester_docker_setup/Dockerfile
  tools/curl_install_tester_docker_setup/README.md
Labels: enhancement
