Repository lfn-cnti/testsuite, pull requests merged in 2021-01, with the labels that each got.

#549 Doc/cnf conformance yml usage #537
  CNF_CONFORMANCE_YML_USAGE.md
Labels: 2 pts, documentation

#556 Link to releases/latest for binary download
  INSTALL.md
Labels: documentation, usability

#570 cnf installation refactor #569
  spec/utils/cnf_manager_spec.cr
  spec/utils/utils_spec.cr
  src/tasks/cnf_setup.cr
  src/tasks/utils/cnf_manager.cr
  src/tasks/utils/utils.cr
Labels: 3 pts

#573 [BUG] After running cnf_setup, cnf-conformance errors "you must provide cnf-config or cnf-path" when running tests after the setup. #572
  spec/platform/platform_spec.cr
  spec/utils/cnf_manager_spec.cr
  spec/utils/utils_spec.cr
  spec/workload/configuration_lifecycle_spec.cr
  spec/workload/installability_spec.cr
  spec/workload/scalability_spec.cr
  spec/workload/security_spec.cr
  src/cnf-conformance.cr
  src/tasks/cnf_setup.cr
  src/tasks/utils/cnf_manager.cr
  src/tasks/utils/helm.cr
  src/tasks/utils/utils.cr
Labels: 2 pts
