Repository lfn-cnti/testsuite, pull requests merged in 2021-05, with the labels that each got.

#758 Adding helm unicode ⎈ for helm tests
  src/tasks/workload/configuration_lifecycle.cr
  src/tasks/workload/installability.cr
Labels: design, emoji

#770 fix unncesasray typo #703
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: documentation

#777 Fixed the example cnf-testsuite.yml as it was outdated
  example-cnfs/coredns/cnf-testsuite.yml
Labels: 1 pt

#779 Feature/#745 clean up binary messaging
  INSTALL.md
  README.md
  curl_install.sh
  spec/curl_install_spec.cr
Labels: 1 pt, enhancement

#783 remove verbose option from tar
  curl_install.sh
Labels: usability
