Repository lfn-cnti/testsuite, pull requests merged in 2024-04, with the labels that each got.

#1897 Update Kind and its image versions in gates
  .github/workflows/actions.yml
Labels: one summit 2024

#1939 Adapt cert tests for CNTI certification V2.0
  embedded_files/points.yml
  spec/utils/cnf_manager_spec.cr
  src/tasks/cert/cert.cr
  src/tasks/cert/cert_microservice.cr
  src/tasks/cert/cert_state.cr
  src/tasks/constants.cr
Labels: one summit 2024

#1978 fix immutable configmaps typo
  src/tasks/workload/configuration.cr
Labels: documentation

#1962 Enhancement: Add test name before and after the test in console output
  spec/5g/core_spec.cr
  spec/5g/ran_spec.cr
  spec/platform/hardware_and_scheduler_spec.cr
  spec/platform/observability_spec.cr
  spec/platform/platform_spec.cr
  spec/platform/resilience_spec.cr
  spec/platform/security_spec.cr
  spec/utils/utils_spec.cr
  spec/workload/compatibility_spec.cr
  spec/workload/configuration_spec.cr
  spec/workload/installability_spec.cr
  spec/workload/microservice_spec.cr
  spec/workload/observability_spec.cr
  spec/workload/operator_spec.cr
  spec/workload/resilience/disk_fill_spec.cr
  spec/workload/resilience/node_drain_spec.cr
  spec/workload/resilience/pod_delete_spec.cr
  spec/workload/resilience/pod_dns_error_spec.cr
  spec/workload/resilience/pod_io_stress_spec.cr
  spec/workload/resilience/pod_memory_hog_spec.cr
  spec/workload/resilience/pod_network_corruption_spec.cr
  spec/workload/resilience/pod_network_duplication_spec.cr
  spec/workload/resilience/pod_network_latency_spec.cr
  spec/workload/security_spec.cr
  spec/workload/state_spec.cr
  src/tasks/utils/task.cr
  src/tasks/utils/utils.cr
Labels: enhancement, usability
